name: build and run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache boost
      uses: actions/cache@v1.0.3
      id: cache-boost
      with:
        path: "~/boost"
        key: libboost1.65-dev-2
    - name: Install boost
      env:
        CACHE_HIT: ${{steps.cache-boost.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" == 'true' ]]; then
          sudo cp --force --recursive ~/boost/* /
        else
          sudo sudo apt-get update && sudo apt-get install -yq libboost1.65-dev clang-format-9
          mkdir -p ~/boost
          for dep in libboost1.65-dev clang-format-9; do
              dpkg -L $dep | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/boost/
          done
        fi


    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -Bbuild -H.
    - name: cmake make
      run: cmake --build build/ --target all
      env:
        MAKEFLAGS: "-j2"

    # Tests start here
    - name: game test
      run: build/src/Game/tst/Game_tst
    - name: commands test
      run: build/src/Commands/tst/Commands_tst
    - name: store test
      run: build/src/Store/tst/Store_tst
    - name: Wallet test
      run: build/src/Wallet/tst/Wallet_tst
    - name: Achievement test
      run: build/src/Achievements/tst/Achievements_tst


    #coding style check
    - name: style check
      run: cmake --build cmake-build-debug/ --target checkstyle

      # upload artifact, game binary
    - name: Upload Game
      uses: actions/upload-artifact@v1
      with:
        name: c_ookieClicker_linux
        path: build/src/Game/src/Game_linux
      
      
