name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache boost
      uses: actions/cache@v1.0.3
      id: cache-boost
      with:
        path: "~/boost"
        key: libboost1.71-dev
    - name: Install boost
      env:
        CACHE_HIT: ${{steps.cache-boost.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" == 'true' ]]; then
          sudo cp --verbose --force --recursive ~/boost/* /
        else
          sudo sudo apt-get update && sudo apt-get install -yq libboost1.71-dev
          mkdir -p ~/boost
          for dep in libboost1.71-dev libc6 libgcc1 gcc-8-base; do
              dpkg -L $dep | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/valgrind/
          done
        fi
#    - name: boost
#      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -Bbuild -H.
    - name: cmake make
      run: cmake --build build/ --target all
    - name: game test
      run: build/src/Game/tst/Game_tst
    - name: commands test
      run: build/src/Commands/tst/Commands_tst
    - name: store test
      run: build/src/Store/tst/Store_tst
    - name: Wallet test
      run: build/src/Wallet/tst/Wallet_tst
    - name: Upload Game.exe
      uses: actions/upload-artifact@v1
      with:
        name: Game.exe
        path: build/src/Game/src/Game.exe
      
      
